volumes:
  postgres-data:
    driver: local
services:
  postgres:
    image: postgres:16.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: password
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ..:/app:cached
      - postgres-data:/var/lib/postgresql/data:cached
