volumes:
  postgres-data:
    driver: local
services:
  postgres:
    image: postgres:16.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: ''
    volumes:
      - ..:/app:cached
      - postgres-data:/var/lib/postgresql/data:cached
