name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Set up Python
        uses: actions/setup-python@v5.2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v3.0.0

      - name: Run tests
        run: |
          chmod +x ./run_tests.sh
          ./run_tests.sh
